# Generated by Django 4.2.5 on 2024-12-08 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pronostic', '0003_pronostic_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(choices=[('SIMPLE', 'Simple'), ('DOUBLE', 'Double')], max_length=255, null=True)),
                ('numbers', models.CharField(max_length=255, null=True)),
                ('win', models.CharField(max_length=255, null=True)),
                ('mac', models.CharField(max_length=255, null=True)),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pronostic.jeux')),
            ],
        ),
    ]
