# Generated by Django 4.2.5 on 2024-12-08 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronostic', '0004_resultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
