# Generated by Django 4.2.5 on 2025-01-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_user_is_commercial_commercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=0.0)),
                ('commercial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.commercial')),
            ],
        ),
    ]
