# Generated by Django 4.2.5 on 2025-01-18 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercial', '0002_portefeuille_gain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_as_client', to=settings.AUTH_USER_MODEL)),
                ('comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_as_commercial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
