# Generated by Django 4.2.5 on 2025-01-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_commercial_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcasseur',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forcasseur',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forcasseur',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
