# Generated by Django 4.2.5 on 2025-01-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_forcasseur_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dashadmin',
            field=models.BooleanField(default=False),
        ),
    ]
