# Generated by Django 4.2.5 on 2024-10-22 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('parieur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.parieur')),
            ],
        ),
    ]
