version: '3.8'

services:
  web:
    build: .
    environment:
      DB_NAME: fortix
      DB_USER: vlad
      DB_PASSWORD: vlad
      DB_HOST: db                  # Nom de service pour accéder à PostgreSQL
      DB_PORT: 5432
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`forti-x.com`)" # Règle de routage pour votre domaine
      - "traefik.http.routers.web.entrypoints=websecure"   # Utilisation de HTTPS
      - "traefik.http.routers.web.tls.certresolver=myresolver" # Let's Encrypt
      - "traefik.http.services.web.loadbalancer.server.port=8000" # Port interne exposé par Django
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fortix           # Nom de la base de données
      POSTGRES_USER: vlad           # Utilisateur de la base de données
      POSTGRES_PASSWORD: vlad       # Mot de passe de l'utilisateur
    ports:
      - "5432:5432"                 # Exposer le port de PostgreSQL
    volumes:
      - db_data:/var/lib/postgresql/data  # Volume pour persister les données

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80" # HTTP
      - "--entrypoints.websecure.address=:443" # Définir le point d'entrée HTTPS
      - "--providers.docker" # Activer le support Docker
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # Défis TLS pour Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.email=dev.vladmir@gmail.com" # Votre e-mail pour Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # Stockage des certificats
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure" # Redirection HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https" # Forcer HTTPS
    ports:
      - "443:443"  # HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Accès au socket Docker
      - "./letsencrypt:/letsencrypt" # Volume pour stocker les certificats

volumes:
  db_data:
  letsencrypt:
